
  // 公寓
 const apartmentData = [
   {
     "id":"1",
     "apartmentName":"十里堡-6号",
     "apartmentManager":"张老师",
     "totalFloor":"6",
     "totalRoom":"300",
     "apartmentType":"6",
     "useDate":"4/10/2019",
     "studentSex":"1",
     "repairCount":"0",
     "sortNum":"0"
   },
   {
     "id":"2",
     "apartmentName":"十里堡-5号",
     "apartmentManager":"赵老师",
     "totalFloor":"6",
     "totalRoom":"300",
     "apartmentType":"6",
     "useDate":"4/10/2019",
     "studentSex":"1",
     "repairCount":"2",
     "sortNum":"1"
   },
   {
     "id":"3",
     "apartmentName":"十里堡-4号",
     "apartmentManager":"钱老师",
     "totalFloor":"5",
     "totalRoom":"200",
     "apartmentType":"4",
     "useDate":"4/10/2019",
     "studentSex":"1",
     "repairCount":"0",
     "sortNum":"2"
   },
   {
     "id":"4",
     "apartmentName":"十里堡-3号",
     "apartmentManager":"孙老师",
     "totalFloor":"6",
     "totalRoom":"300",
     "apartmentType":"4",
     "useDate":"4/10/2019",
     "studentSex":"2",
     "repairCount":"0",
     "sortNum":"3"
   },
   {
     "id":"5",
     "apartmentName":"十里堡-2号",
     "apartmentManager":"李老师",
     "totalFloor":"5",
     "totalRoom":"200",
     "apartmentType":"6",
     "useDate":"4/10/2019",
     "studentSex":"1",
     "repairCount":"0",
     "sortNum":"4"
   },
   {
     "id":"6",
     "apartmentName":"十里堡-1号",
     "apartmentManager":"周老师",
     "totalFloor":"6",
     "totalRoom":"300",
     "apartmentType":"6",
     "useDate":"4/10/2019",
     "studentSex":"2",
     "repairCount":"0",
     "sortNum":"5"
   }
 ];
  export {apartmentData}
